RootNode:
    BaseClass: System.Windows.Forms.UserControl
    UtilObjectClass: TFrmPetraEditUtils
    Namespace: Ict.Petra.Client.MPartner.Gui   
    UsingNamespaces: [Ict.Petra.Shared.MPersonnel.Personnel.Data]
    #DatasetType: Ict.Petra.Shared.MPersonnel.Personnel.Data.ApplicationTDS
    FormType: edit
    Template: usercontrolUnbound
    #MasterTable: PmGeneralApplication

    Controls:
        pnlContent:
            Dock: Fill
            Controls: [tabApplicationEvent]

        tabApplicationEvent:
            DragTabPageEnabled: false
            ShowToolTips: true
            LoadPagesDynamically: false
            IgnoreFirstTabPageSelectionChange: true
            Dock: Fill
        
        tpgEvent:
            Label: Event
            Controls: [ucoEvent]

        tpgApplicant:
            Label: Applicant
            Controls: [ucoApplicant]

        tpgTravel:
            Label: Travel
            Controls: [ucoTravel]

        ucoEvent:
            Dock: Fill
            Type: Ict.Petra.Client.MPartner.Gui.TUC_ApplicationPage_Event
        ucoApplicant:
            Dock: Fill
            Type: Ict.Petra.Client.MPartner.Gui.TUC_ApplicationPage_Applicant_Event
        ucoTravel:
            Dock: Fill
            Type: Ict.Petra.Client.MPartner.Gui.TUC_ApplicationPage_Travel
