RootNode:
    BaseClass: System.Windows.Forms.UserControl
    UtilObjectClass: TFrmPetraEditUtils
    Namespace: Ict.Petra.Client.MPartner.Gui   
    UsingNamespaces: [Ict.Petra.Shared.MPersonnel.Personnel.Data,Ict.Petra.Shared.MPersonnel.Personnel.Validation]
    #DatasetType: Ict.Petra.Shared.MPersonnel.Personnel.Data.ApplicationTDS
    FormType: edit
    Template: usercontrolUnbound
    #MasterTable: PmGeneralApplication

    Controls:
        pnlContent:
            Dock: Fill
            Controls: [tabApplicationField]

        tabApplicationField:
            DragTabPageEnabled: false
            ShowToolTips: true
            LoadPagesDynamically: false
            IgnoreFirstTabPageSelectionChange: true
            Dock: Fill
        
        tpgField:
            Label: Field
            Controls: [ucoField]

        tpgApplicant:
            Label: Applicant
            Controls: [ucoApplicant]

        ucoField:
            Dock: Fill
            Type: Ict.Petra.Client.MPartner.Gui.TUC_ApplicationPage_Field
        ucoApplicant:
            Dock: Fill
            Type: Ict.Petra.Client.MPartner.Gui.TUC_ApplicationPage_Applicant_Field
