RootNode:
    BaseClass: System.Windows.Forms.UserControl
    UtilObjectClass: TFrmPetraEditUtils
    Namespace: Ict.Petra.Client.MPartner.Gui   
    UsingNamespaces: [Ict.Petra.Shared.MPersonnel.Personnel.Data]
    DatasetType: Ict.Petra.Shared.MPersonnel.Personnel.Data.ApplicationTDS
    FormType: edit
    Template: usercontrol
    MasterTable: PmGeneralApplication
    Actions:
    Controls:
        pnlDetails:
            Controls: [grpEventInfo, grpMiscellaneous]
            Dock: Fill
        grpEventInfo: {NoLabel=true}
            Controls: 
                Row0: [txtEvent]
                Row1: [txtFieldCharged]
        grpMiscellaneous: {NoLabel=true}
            Controls: 
                Row0: [cmbContact1]
                Row1: [cmbContact2]
                Row2: [txtPlacementPerson]
              
        txtEvent: {Label=Event, DataField=PmShortTermApplication.StConfirmedOption, Type=PartnerKey}
        txtFieldCharged: {Label=Field Charged, DataField=PmShortTermApplication.StFieldCharged, Type=PartnerKey}

        cmbContact1: {Label= Organization Contact 1, List=ContactList, DataField=PmGeneralApplication.GenContact1}
        cmbContact2: {Label= Organization Contact 2, List=ContactList, DataField=PmGeneralApplication.GenContact2}
        txtPlacementPerson: {Label=Placement Person, DataField=PmGeneralApplication.PlacementPartnerKey, Type=PartnerKey}
        
