RootNode:
    BaseClass: System.Windows.Forms.UserControl
    UtilObjectClass: TFrmPetraEditUtils
    Namespace: Ict.Petra.Client.MPartner.Gui   
    UsingNamespaces: [Ict.Petra.Shared.MPersonnel.Personnel.Data]
    DatasetType: Ict.Petra.Shared.MPersonnel.Personnel.Data.ApplicationTDS
    FormType: edit
    Template: usercontrol
    MasterTable: PmGeneralApplication
    Actions:
    Controls:
        pnlDetails:
            Controls: [grpEventInfo, grpMiscellaneous]
            Dock: Fill
        grpEventInfo: {NoLabel=true, Stretch=horizontally}
            Controls: 
                #Row0: [lblEvent, btnEvent, txtEvent, lblEventName1]
                Row0: [txtEvent]
                Row1: [txtFieldCharged]
        grpMiscellaneous: {NoLabel=true, Stretch=horizontally}
            Controls: 
                Row0: [cmbApplicationType]
                Row1: [cmbContact1]
                Row2: [cmbContact2]
                Row3: [txtPlacementPerson]
              
        #lblEvent: {Label=Event}
        #btnEvent: {Label=Find, OnClick=OnBtnEventClicked}
        #txtEvent: {NoLabel=true}
        #lblEventName1: {Label=test}
        txtEvent: {Label=Event, DataField=PmShortTermApplication.StConfirmedOption, Type=PartnerKey, OnChange=ProcessApplicationEventChanged}
        txtFieldCharged: {Label=Field Charged, DataField=PmShortTermApplication.StFieldCharged, Type=Conference, PartnerClass=UNIT}

        cmbApplicationType: {Label=Application Type, List=EventApplicationTypeList, DataField=PmGeneralApplication.AppTypeName}
        cmbContact1: {Label=Organization Contact 1, List=ContactList, DataField=PmGeneralApplication.GenContact1}
        cmbContact2: {Label=Organization Contact 2, List=ContactList, DataField=PmGeneralApplication.GenContact2}
        txtPlacementPerson: {Label=Placement Person, DataField=PmGeneralApplication.PlacementPartnerKey, Type=PartnerKey, PartnerClass=PERSON}
        
