RootNode:
    BaseClass: System.Windows.Forms.UserControl
    UtilObjectClass: TFrmPetraEditUtils
    Namespace: Ict.Petra.Client.MPartner.Gui   
    UsingNamespaces: [Ict.Petra.Shared.MPartner.Partner.Data]
    DatasetType: Ict.Petra.Shared.MPartner.Partner.Data.PartnerEditTDS
    FormType: edit
    Template: usercontrolUnbound
    Controls:
        pnlContent:
            Controls: [lblTodo]
            Dock: Fill

        lblTodo: