RootNode:
    BaseClass: System.Windows.Forms.UserControl
    UtilObjectClass: TFrmPetraEditUtils
    Namespace: Ict.Petra.Client.MPartner.Gui   
    UsingNamespaces: [Ict.Petra.Shared.MPersonnel.Personnel.Data]
    DatasetType: Ict.Petra.Shared.MPersonnel.Personnel.Data.ApplicationTDS
    FormType: edit
    Template: usercontrol
    MasterTable: PmGeneralApplication
    Actions:
    Controls:
        pnlDetails:
            Controls: [grpComments, grpStatus, grpFinance]
            Dock: Fill
        grpComments: {Label=Additional Preferences or Comments, Stretch=horizontally}
            Controls: 
                Row0: [txtComments]
        grpStatus: {Label=Status, Stretch=horizontally}
            Controls: 
                Row0: [cmbApplicationStatus]
                Row1: [txtReason]
                Row2: [dtpCancellationDate, dtpAcceptanceDate]
                Row3: [chkAcceptedByReceivingField, dtpFieldAcceptance]
        grpFinance: {Label=Finance, Stretch=horizontally}
            Controls: 
                Row0: [cmbApplicationCurrency]
                Row1: [txtJoiningCharge, txtAgreedSupport]
                Row2: [cmbSupportPeriod]
              
        txtComments: {NoLabel=true, DataField=PmGeneralApplication.Comment, Stretch=horizontally}
            Width: 600
            Height: 50
            Multiline: true
            ScrollBars: Vertical
            
        cmbApplicationStatus: {Label=Application Status, List=ApplicantStatusList, DataField=PmGeneralApplication.GenApplicationStatus, ColSpan=2}
        txtReason: {Label=Reason, DataField=PmGeneralApplication.GenApplicationHoldReason, ColSpan=2, Stretch=horizontally}
        dtpCancellationDate: {Label= Cancellation Date, DataField=PmGeneralApplication.GenAppCancelled}
        dtpAcceptanceDate: {Label=Sending Field Acceptance Date, DataField=PmGeneralApplication.GenAppSendFldAcceptDate}
        chkAcceptedByReceivingField: {Label=Accepted by Receiving Field, DataField=PmGeneralApplication.GenAppSrvFldAccept, OnChange=EnableDisableReceivingFieldAcceptanceDate}
        dtpFieldAcceptance: {Label=Receiving Field Acceptance Date, DataField=PmGeneralApplication.GenAppRecvgFldAccept, Validation=true}
        
        cmbApplicationCurrency: {Label=Application Currency, List=CurrencyCodeList, DataField=PmGeneralApplication.GenAppCurrencyCode, OnChange=ApplicationCurrencyChanged, ColSpan=2}
        txtJoiningCharge: {Label=Joining Charge, Format=Currency, DataField=PmYearProgramApplication.YpAgreedJoiningCharge}
        txtAgreedSupport: {Label=Agreed Support, Format=Currency, DataField=PmYearProgramApplication.YpAgreedSupportFigure}
        cmbSupportPeriod: {Label=Support Period, DataField=PmYearProgramApplication.YpSupportPeriod, ColSpan=2}
        