RootNode:
    BaseClass: System.Windows.Forms.UserControl
    UtilObjectClass: TFrmPetraEditUtils
    Namespace: Ict.Petra.Client.MPartner.Gui   
    UsingNamespaces: [Ict.Petra.Shared.MPartner.Partner.Data]
    FormType: edit
    Template: usercontrolUnbound
    Actions:
    Controls:
        pnlContent:
            Controls: [ucoApplications]              
            Dock: Fill

        ucoApplications:
            Dock: Fill
            Type: Ict.Petra.Client.MPartner.Gui.TUC_Applications
