  RootNode:
    BaseYaml: ../../CommonForms/PetraFormDialog.yaml
    FormTitle: Intranet Export Settings
    Namespace: Ict.Petra.Client.MSysMan.Gui
    FormType: dialog
    Template: window
    WindowWidth: 350
    WindowHeight:250

    Controls:
        pnlDialogContent:
            Controls: [txtDonationDays, txtOptionalMetadata, grpPassword]

        txtDonationDays:
            Format: Integer
        txtOptionalMetadata:
        grpPassword:
            Controls: [txtOldPassword, txtNewPassword, txtConfirmPassword]
        txtOldPassword:
            PasswordEntry: true
        txtNewPassword:
            PasswordEntry: true
        txtConfirmPassword:
            PasswordEntry: true