RootNode:
    BaseClass: UserControl
    UtilObjectClass: TFrmPetraReportingUtils
    Namespace: Ict.Petra.Client.MReporting.Gui.MFinance
    DatasetType: Ict.Petra.Shared.MFinance.GL.Data.GLSetupTDS
    FormType: edit
    Template: usercontrolUnbound
    UsingNamespaces: [Ict.Common.Data]
    Actions:
        actUnselectAllCostCentres:
            ActionClick: UnselectAllCostCentres
        actUnselectAllAccountCodes:
            ActionClick: UnselectAllAccountCodes
        actSelectAllReportingCostCentres:
            ActionClick: SelectAllReportingCostCentres
    Controls:
        pnlContent:
            Controls: [rgrAccountCodes, rgrCostCentre]
            Dock: Fill
            
        rgrAccountCodes: 
            ParameterName: param_account_codes
            Controls: [rbtAccountRange, rbtAccountFromList]
            Label: Select Account Codes
        rbtAccountRange:
            Label: Select Range
            Controls: [cmbFromAccountCode, cmbToAccountCode]
        rbtAccountFromList:
            Label: From List
            Controls: [clbAccountCodes, btnUnselectAllAccountCodes]
            ControlsOrientation: horizontal
            
        rgrCostCentre: 
            ParameterName: param_costcentreoptions
            Controls: [rbtCostCentreRange, rbtCostCentreFromList]
            Label: Select Cost Centre Codes
        rbtCostCentreRange:
            Label: Select Range
            Controls: [cmbFromCostCentre, cmbToCostCentre]
        rbtCostCentreFromList:
            Label: From List
            Controls: [pnlCostCentreFromList]
        pnlCostCentreFromList:
            Controls: 
                Row0: [clbCostCentres, btnUnselectAllCostCentres]
                Row1: [cmbSummaryCostCentres]
                Row2: [btnSelectAllReportingCostCentres]
        
        clbAccountCodes: 
            List: UserDefinedList
            NoLabel:true
            Width: 365
        btnUnselectAllAccountCodes: 
            Label: Unselect All
            Action: actUnselectAllAccountCodes
        cmbFromAccountCode:
            List: UserDefinedList
            Label: From
        cmbToAccountCode:
            List: UserDefinedList
            Label: To
        cmbFromCostCentre:
            List: UserDefinedList
            Label: From
        cmbToCostCentre:
            List: UserDefinedList
            Label: To
        cmbSummaryCostCentres:
            ColSpan: 2
            List: UserDefinedList
            Label: Summary Cost Centres
        clbCostCentres: 
            List: UserDefinedList
            NoLabel:true
            Width: 365
        btnUnselectAllCostCentres: 
            Label: Unselect All
            Action: actUnselectAllCostCentres
        btnSelectAllReportingCostCentres:
            Label: Tick all reporting cost centres
     