RootNode:
    BaseClass: UserControl
    UtilObjectClass: TFrmPetraReportingUtils
    Namespace: Ict.Petra.Client.MReporting.Gui.MFinance
    DatasetType: Ict.Petra.Shared.MFinance.GL.Data.GLSetupTDS
    FormType: edit
    Template: usercontrolUnbound
    UsingNamespaces: [Ict.Common.Data]
    Actions:
        actUnselectAllCostCentres:
            ActionClick: UnselectAllCostCentres
        actUnselectAllAccountCodes:
            ActionClick: UnselectAllAccountCodes
    Controls:
        pnlContent:
            Controls: [rgrAccountCodes, rgrCostCentre]
            Dock: Fill
            
        rgrAccountCodes: 
            ParameterName: param_account_codes
            Controls: [rbtAccountRange, rbtAccountFromList]
            Label: Select Account Codes
        rbtAccountRange:
            Label: Select Range
            Controls: [cmbFromAccountCode, cmbToAccountCode]
        rbtAccountFromList:
            Label: From List
            Controls: [clbAccountCodes, btnUnselectAllAccountCodes]
            ControlsOrientation: horizontal
            
        rgrCostCentre: 
            ParameterName: param_costcentreoptions
            Controls: [rbtCostCentreRange, rbtCostCentreFromList]
            Label: Select Cost Centre Codes
        rbtCostCentreRange:
            Label: Select Range
            Controls: [cmbFromCostCentre, cmbToCostCentre]
        rbtCostCentreFromList:
            Label: From List
            Controls: [clbCostCentres, btnUnselectAllCostCentres]
            ControlsOrientation: horizontal
        
        clbAccountCodes: 
            List: UserDefinedList
            NoLabel:true
            Dock: Fill
            Width: 365
        btnUnselectAllAccountCodes: 
            Label: Unselect All
            Action: actUnselectAllAccountCodes
        cmbFromAccountCode:
            List: UserDefinedList
            Label: From
        cmbToAccountCode:
            List: UserDefinedList
            Label: To
        cmbFromCostCentre:
            List: UserDefinedList
            Label: From
        cmbToCostCentre:
            List: UserDefinedList
            Label: To
        clbCostCentres: 
            List: UserDefinedList
            NoLabel:true
            Dock: Fill
            Width: 365
        btnUnselectAllCostCentres: 
            Label: Unselect All
            Action: actUnselectAllCostCentres
        
     